# Generated by Django 4.2.3 on 2023-11-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_abonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
