# Generated by Django 4.2.3 on 2023-11-09 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_abonnement_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message',
        ),
    ]
