# Generated by Django 4.2.3 on 2023-11-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_content_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='ville',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
