# Generated by Django 4.2.3 on 2023-11-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_abonnements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Abonnement',
        ),
    ]
