# Generated by Django 4.2.3 on 2023-11-12 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_abonnements_lastmsg_abonnement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='lastMsg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chat.message'),
        ),
    ]
