# Generated by Django 4.2.3 on 2023-11-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_abonnements_lastmsg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='LastMsg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='dateLastMsg',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='userLastMsg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
