# Generated by Django 4.2.3 on 2023-11-12 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_abonnement_lastmsg_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Abonnements',
        ),
    ]
