# Generated by Django 4.2.3 on 2023-11-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_delete_abonnements'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='heuresLastMsg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='joursMsg',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='minLastMsg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='secLastMsg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
