# Generated by Django 4.2.3 on 2023-11-12 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_rename_joursmsg_abonnement_jourslastmsg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonnement',
            name='heuresLastMsg',
        ),
        migrations.RemoveField(
            model_name='abonnement',
            name='joursLastMsg',
        ),
        migrations.RemoveField(
            model_name='abonnement',
            name='minLastMsg',
        ),
        migrations.RemoveField(
            model_name='abonnement',
            name='secLastMsg',
        ),
    ]
