# Generated by Django 4.2.3 on 2023-10-20 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Compte',
        ),
    ]
