# Generated by Django 4.2.3 on 2023-10-28 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
