# Generated by Django 4.2.3 on 2023-10-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='adresse',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
